# Site settings
title:  forever✰ space for contemporary art 
email: forevershadwoedwhitestar@gmail.com
description: > # keep this and put description below
  Art, community
url: "https://forevercontemporary.org" # the base hostname & protocol for your site
twitter_url: "https://instagram.com/forever.shadowed.white.star"
 
footer_text: "    forever✰ space for contemporary art "

# Build settings
markdown: kramdown
permalink: pretty

collections:
  - staff_members
  - residency
